name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      working-directory: .
      run: pytest tests/
    - name: Run preprocessing
      working-directory: .
      run: python src/data_preprocessing.py
    - name: Run model training
      working-directory: .
      run: python src/model_training.py
    - name: Check output files
      run: |
        test -f data/processed/model_results.csv
        test -f data/processed/plots/cm_LogisticRegression_Fraud_Data.png